# Preprocess Player Stats & History

## Preprocess player Stats
- drop mystery empty row
- convert date format to datetime64[ns](i.e. 2022-06-21)
- remove duplicate
- remove "FakePlayer"
- rename player's name according to id_conversion_table

### Read In CSV File

In [1]:
import pandas as pd

original_data_22 = pd.read_csv('datasets/FIFA22_player_stats.csv')
original_data_22

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Kevin De Bruyne,192985.0,21-Jun-22,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
1,Kevin De Bruyne,192985.0,15-Jun-22,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
2,Kevin De Bruyne,192985.0,13-Jun-22,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
3,Kevin De Bruyne,192985.0,2-Jun-22,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
4,Kevin De Bruyne,192985.0,30-May-22,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210241,Geovani,2.0,28-Oct-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210242,Geovani,2.0,25-Oct-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210243,Geovani,2.0,21-Oct-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210244,Geovani,2.0,18-Oct-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210245,Geovani,2.0,8-Oct-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0

In [2]:
original_data_21 = pd.read_csv('datasets/FIFA21_player_stats.csv')
original_data_21

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Kevin De Bruyne,192985,16-Sep-21,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
1,Kevin De Bruyne,192985,2-Sep-21,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
2,Kevin De Bruyne,192985,26-Aug-21,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
3,Kevin De Bruyne,192985,5-Aug-21,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
4,Kevin De Bruyne,192985,2-Aug-21,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282885,Mauro Caballero,212943,8-Oct-20,175,72,Left,26,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282886,Mauro Caballero,212943,5-Oct-20,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282887,Mauro Caballero,212943,1-Oct-20,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282888,Mauro Caballero,212943,23-Sep-20,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282889,Mauro Caballero,212943,24-Aug-20,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9

### Remove empty row

In [3]:
nan_value = float("NaN")

print("shape of 22 before removing: ", original_data_22.shape)
original_data_22.replace("", nan_value, inplace=True)

original_data_22.dropna(axis = 0, how = 'all', inplace=True)
print("after removing: ", original_data_22.shape)

print("shape of 21 before removing: ", original_data_21.shape)
original_data_21.replace("", nan_value, inplace=True)

original_data_21.dropna(axis = 0, how = 'all', inplace=True)
print("after removing: ", original_data_21.shape)

shape of 22 before removing:  (210246, 43)
after removing:  (210192, 43)
shape of 21 before removing:  (282890, 43)
after removing:  (282890, 43)

### Convert Date Formats and Change ID format for FIFA22

In [4]:
original_data_22['stat_date'] = pd.to_datetime(original_data_22['stat_date'])
original_data_22['ID'] = original_data_22['ID'].astype(int)

original_data_22

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Kevin De Bruyne,192985,2022-06-21,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
1,Kevin De Bruyne,192985,2022-06-15,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
2,Kevin De Bruyne,192985,2022-06-13,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
3,Kevin De Bruyne,192985,2022-06-02,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
4,Kevin De Bruyne,192985,2022-05-30,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210241,Geovani,2,2021-10-28,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210242,Geovani,2,2021-10-25,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210243,Geovani,2,2021-10-21,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210244,Geovani,2,2021-10-18,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0
210245,Geovani,2,2021-10-08,181.0,75.0,Left,20.0,Famalicão,75.0,65.0,...,59.0,63.0,54.0,63.0,62.0,6.0,7.0,10.0,13.0,8.0

### Convert Date Formats for FIFA21

In [5]:
original_data_21['stat_date'] = pd.to_datetime(original_data_21['stat_date'])

original_data_21

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Kevin De Bruyne,192985,2021-09-16,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
1,Kevin De Bruyne,192985,2021-09-02,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
2,Kevin De Bruyne,192985,2021-08-26,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
3,Kevin De Bruyne,192985,2021-08-05,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
4,Kevin De Bruyne,192985,2021-08-02,181,70,Right,30,Manchester City,17,92,...,91,85,83,83,82,10,15,13,5,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282885,Mauro Caballero,212943,2020-10-08,175,72,Left,26,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282886,Mauro Caballero,212943,2020-10-05,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282887,Mauro Caballero,212943,2020-10-01,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282888,Mauro Caballero,212943,2020-09-23,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9
282889,Mauro Caballero,212943,2020-08-24,175,72,Left,25,Unión Española,9,63,...,52,51,40,70,61,9,14,16,10,9

### Remove Duplicate For Both

In [6]:
print("shape of 22 before removing: ", original_data_22.shape)
original_data_22.drop_duplicates(keep='first', inplace=True)
print("after removing: ", original_data_22.shape)

print("shape of 21 before removing: ", original_data_21.shape)
original_data_21.drop_duplicates(keep='first', inplace=True)
print("after removing: ", original_data_21.shape)

shape of 22 before removing:  (210192, 43)
after removing:  (206452, 43)
shape of 21 before removing:  (282890, 43)
after removing:  (272546, 43)

### Remove "FakePlayer" For Both

In [7]:
print("shape of 22 before removing: ", original_data_22.shape)
original_data_22 = original_data_22[original_data_22['name'] != 'FakePlayer']
original_data_22 = original_data_22.reset_index(drop=True)
print("after removing: ", original_data_22.shape)

print("shape of 21 before removing: ", original_data_21.shape)
original_data_21 = original_data_21[original_data_21['name'] != 'FakePlayer']
original_data_21 = original_data_21.reset_index(drop=True)
print("after removing: ", original_data_21.shape)

shape of 22 before removing:  (206452, 43)
after removing:  (206452, 43)
shape of 21 before removing:  (272546, 43)
after removing:  (272546, 43)

### Rename Players For Both

#### 2022

In [8]:
id_conversion = pd.read_csv('datasets/id_conversion_table.csv')

# Remove empty row
nan_value = float("NaN")

print("shape before removing: ", id_conversion.shape)
id_conversion.replace("", nan_value, inplace=True)

id_conversion.dropna(axis = 0, how = 'all', inplace=True)
print("after removing: ", id_conversion.shape)

# change data type
id_conversion['ID'] = id_conversion['ID'].astype(int)
#id_conversion['kit_number'] = id_conversion['kit_number'].astype(int)

id_conversion

shape before removing:  (3626, 4)
after removing:  (3625, 4)

          ID                  name               team  kit_number
0     192985       Kevin De Bruyne    Manchester City        17.0
1      20801     Cristiano Ronaldo  Manchester United         7.0
2     203376       Virgil van Dijk          Liverpool         4.0
3     212831               Alisson          Liverpool         1.0
4     210257               Ederson    Manchester City        31.0
...      ...                   ...                ...         ...
3621  220517  Francesco Di Mariano                NaN         NaN
3622  202550     Anderson Carvalho                NaN         NaN
3623  234499         Pedro Sánchez                NaN         NaN
3624  212943       Mauro Caballero                NaN         NaN
3625       2               Geovani                NaN         NaN

[3625 rows x 4 columns]

In [9]:
# Renaming FIFA22
for i, row in original_data_22.iterrows():
    # Get Name from id_conversion
    name = id_conversion[id_conversion['ID'] == row['ID']].iloc[0]['name']
    
    # Replace the name in dataframe
    original_data_22.at[i,'name'] = name

In [10]:
original_data_22[original_data_22['ID'] == 203376].head()

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
116,Virgil van Dijk,203376,2022-06-21,193.0,92.0,Right,30.0,Liverpool,4.0,76.0,...,64.0,60.0,70.0,62.0,45.0,11.0,13.0,10.0,13.0,11.0
117,Virgil van Dijk,203376,2022-06-15,193.0,92.0,Right,30.0,Liverpool,4.0,76.0,...,64.0,60.0,70.0,62.0,45.0,11.0,13.0,10.0,13.0,11.0
118,Virgil van Dijk,203376,2022-06-13,193.0,92.0,Right,30.0,Liverpool,4.0,76.0,...,64.0,60.0,70.0,62.0,45.0,11.0,13.0,10.0,13.0,11.0
119,Virgil van Dijk,203376,2022-06-02,193.0,92.0,Right,30.0,Liverpool,4.0,76.0,...,64.0,60.0,70.0,62.0,45.0,11.0,13.0,10.0,13.0,11.0
120,Virgil van Dijk,203376,2022-05-30,193.0,92.0,Right,30.0,Liverpool,4.0,76.0,...,64.0,60.0,70.0,62.0,45.0,11.0,13.0,10.0,13.0,11.0

#### 2021

In [11]:
id_conversion2 = pd.read_csv('datasets/id_conversion_table2.csv')

# Remove empty row(only rows that are all empty)
nan_value = float("NaN")

print("shape before removing: ", id_conversion2.shape)
id_conversion2.replace("", nan_value, inplace=True)

id_conversion2.dropna(axis = 0, how = 'all', inplace=True)
print("after removing: ", id_conversion2.shape)

# change data type
# id_conversion2['ID'] = id_conversion2['ID'].astype(int)
# id_conversion2['kit_number'] = id_conversion2['kit_number'].astype(int)

id_conversion2

shape before removing:  (4564, 4)
after removing:  (4564, 4)

          ID                   name               team  kit_number
0     192985        Kevin De Bruyne    Manchester City        17.0
1     209331          Mohamed Salah          Liverpool        11.0
2     203376        Virgil van Dijk          Liverpool         4.0
3     212831                Alisson          Liverpool         1.0
4     202126             Harry Kane  Tottenham Hotspur        10.0
...      ...                    ...                ...         ...
4559  198811  Fredrik Oldrup Jensen                NaN         NaN
4560  220517   Francesco Di Mariano                NaN         NaN
4561  202550      Anderson Carvalho                NaN         NaN
4562  234499          Pedro Sánchez                NaN         NaN
4563  212943        Mauro Caballero                NaN         NaN

[4564 rows x 4 columns]

In [12]:
# Renaming FIFA21
for i, row in original_data_21.iterrows():
    # Get Name from id_conversion2
    name = id_conversion2[id_conversion2['ID'] == row['ID']].iloc[0]['name']
    
    # Replace the name in dataframe
    original_data_21.at[i,'name'] = name

In [13]:
original_data_21[original_data_21['ID'] == 213648].head()

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
2787,Pierre-Emile Hojbjerg,213648,2021-09-16,185,84,Right,26,Tottenham Hotspur,5,80,...,79,70,74,51,60,11,9,7,12,11
2788,Pierre-Emile Hojbjerg,213648,2021-09-02,185,84,Right,26,Tottenham Hotspur,5,80,...,79,70,74,51,60,11,9,7,12,11
2789,Pierre-Emile Hojbjerg,213648,2021-08-26,185,84,Right,26,Tottenham Hotspur,5,80,...,79,70,74,51,60,11,9,7,12,11
2790,Pierre-Emile Hojbjerg,213648,2021-08-05,185,84,Right,26,Tottenham Hotspur,5,80,...,79,70,74,51,60,11,9,7,12,11
2791,Pierre-Emile Hojbjerg,213648,2021-08-02,185,84,Right,25,Tottenham Hotspur,5,80,...,79,70,74,51,60,11,9,7,12,11

### Save CSV File
shape of 22: (206100, 43)

shape of 21: (272297, 43)

In [14]:
# size should be 478397 rows × 43 columns
merged = original_data_22.append(original_data_21)
merged

C:\Users\sunny\AppData\Local\Temp\ipykernel_19008\1862564418.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged = original_data_22.append(original_data_21)

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Kevin De Bruyne,192985,2022-06-21,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
1,Kevin De Bruyne,192985,2022-06-15,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
2,Kevin De Bruyne,192985,2022-06-13,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
3,Kevin De Bruyne,192985,2022-06-02,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
4,Kevin De Bruyne,192985,2022-05-30,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272541,Mauro Caballero,212943,2020-10-08,175.0,72.0,Left,26.0,Unión Española,9.0,63.0,...,52.0,51.0,40.0,70.0,61.0,9.0,14.0,16.0,10.0,9.0
272542,Mauro Caballero,212943,2020-10-05,175.0,72.0,Left,25.0,Unión Española,9.0,63.0,...,52.0,51.0,40.0,70.0,61.0,9.0,14.0,16.0,10.0,9.0
272543,Mauro Caballero,212943,2020-10-01,175.0,72.0,Left,25.0,Unión Española,9.0,63.0,...,52.0,51.0,40.0,70.0,61.0,9.0,14.0,16.0,10.0,9.0
272544,Mauro Caballero,212943,2020-09-23,175.0,72.0,Left,25.0,Unión Española,9.0,63.0,...,52.0,51.0,40.0,70.0,61.0,9.0,14.0,16.0,10.0,9.0
272545,Mauro Caballero,212943,2020-08-24,175.0,72.0,Left,25.0,Unión Española,9.0,63.0,...,52.0,51.0,40.0,70.0,61.0,9.0,14.0,16.0,10.0,9.0

In [15]:
# Drop duplicate
print("shape before removing: ", merged.shape)
merged.drop_duplicates(keep='first', inplace=True)
print("after removing: ", merged.shape)

shape before removing:  (478998, 43)
after removing:  (478800, 43)

In [16]:
merged.sort_values(['ID', 'stat_date'], ascending=[False, False], inplace=True)

merged

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
33609,Lewis Payne,268788,2022-06-21,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
33610,Lewis Payne,268788,2022-06-15,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
33611,Lewis Payne,268788,2022-06-13,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
33612,Lewis Payne,268788,2022-06-02,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
33613,Lewis Payne,268788,2022-05-30,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206141,Gavi,1,2021-10-28,173.0,68.0,Right,16.0,Barcelona,30.0,75.0,...,55.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
206142,Gavi,1,2021-10-25,173.0,68.0,Right,16.0,Barcelona,30.0,74.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
206143,Gavi,1,2021-10-21,173.0,68.0,Right,16.0,Barcelona,30.0,74.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
206144,Gavi,1,2021-10-18,173.0,68.0,Right,16.0,Barcelona,30.0,73.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
206145,Gavi,1,2021-10-08,173.0,68.0,Right,16.0,Barcelona,30.0,73.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0

In [17]:
merged.reset_index(drop=True, inplace=True)

merged

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
0,Lewis Payne,268788,2022-06-21,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
1,Lewis Payne,268788,2022-06-15,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
2,Lewis Payne,268788,2022-06-13,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
3,Lewis Payne,268788,2022-06-02,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
4,Lewis Payne,268788,2022-05-30,178.0,73.0,Right,18.0,Southampton,61.0,47.0,...,30.0,37.0,34.0,39.0,29.0,10.0,11.0,9.0,5.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478795,Gavi,1,2021-10-28,173.0,68.0,Right,16.0,Barcelona,30.0,75.0,...,55.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
478796,Gavi,1,2021-10-25,173.0,68.0,Right,16.0,Barcelona,30.0,74.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
478797,Gavi,1,2021-10-21,173.0,68.0,Right,16.0,Barcelona,30.0,74.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
478798,Gavi,1,2021-10-18,173.0,68.0,Right,16.0,Barcelona,30.0,73.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0
478799,Gavi,1,2021-10-08,173.0,68.0,Right,16.0,Barcelona,30.0,73.0,...,54.0,65.0,47.0,51.0,46.0,7.0,8.0,10.0,11.0,13.0

In [18]:
# test
merged[merged['ID']==192985]

,name,ID,stat_date,height,weight,preferred_foot,age,team,kit_number,ball_control,...,long_shots,curve,fk_acc,penalties,volleys,gk_positioning,gk_diving,gk_handling,gk_kicking,gk_reflexes
419631,Kevin De Bruyne,192985,2022-06-21,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
419632,Kevin De Bruyne,192985,2022-06-15,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
419633,Kevin De Bruyne,192985,2022-06-13,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
419634,Kevin De Bruyne,192985,2022-06-02,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
419635,Kevin De Bruyne,192985,2022-05-30,181.0,70.0,Right,30.0,Manchester City,17.0,90.0,...,91.0,85.0,83.0,83.0,83.0,10.0,15.0,13.0,5.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419746,Kevin De Bruyne,192985,2020-10-08,181.0,70.0,Right,29.0,Manchester City,17.0,92.0,...,91.0,85.0,83.0,84.0,82.0,10.0,15.0,13.0,5.0,13.0
419747,Kevin De Bruyne,192985,2020-10-05,181.0,70.0,Right,29.0,Manchester City,17.0,92.0,...,91.0,85.0,83.0,84.0,82.0,10.0,15.0,13.0,5.0,13.0
419748,Kevin De Bruyne,192985,2020-10-01,181.0,70.0,Right,29.0,Manchester City,17.0,92.0,...,91.0,85.0,83.0,84.0,82.0,10.0,15.0,13.0,5.0,13.0
419749,Kevin De Bruyne,192985,2020-09-23,181.0,70.0,Right,29.0,Manchester City,17.0,92.0,...,91.0,85.0,83.0,84.0,82.0,10.0,15.0,13.0,5.0,13.0
419750,Kevin De Bruyne,192985,2020-08-24,181.0,70.0,Right,29.0,Manchester City,17.0,92.0,...,91.0,85.0,83.0,82.0,82.0,10.0,15.0,13.0,5.0,13.0

In [19]:
header = list(original_data_22.columns)

print(header)
print(len(header))

['name', 'ID', 'stat_date', 'height', 'weight', 'preferred_foot', 'age', 'team', 'kit_number', 'ball_control', 'dribbling', 'marking', 'slide_tackle', 'stand_tackle', 'aggression', 'reactions', 'att_position', 'interceptions', 'vision', 'composure', 'crossing', 'short_pass', 'long_pass', 'acceleration', 'stamina', 'strength', 'balance', 'sprint_speed', 'agility', 'jumping', 'heading', 'shot_power', 'finishing', 'long_shots', 'curve', 'fk_acc', 'penalties', 'volleys', 'gk_positioning', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_reflexes']
43

In [20]:
original_data_22.to_csv('pre-processed/FIFA22_player_stats.csv', index = False, header = header, encoding='utf-8-sig')
original_data_21.to_csv('pre-processed/FIFA21_player_stats.csv', index = False, header = header, encoding='utf-8-sig')
merged.to_csv('pre-processed/player_stats.csv', index = False, header = header, encoding='utf-8-sig')

## Preprocess History
- drop empty row(if any)
- remove duplicate(if any)
- convert date format to datetime64[ns](i.e. 2022-06-21)
- add 1 to result
- remove possible space behind names
- convert team shape to positions(team1_shape -> team1_positions_x, team1_positions_y)

### Read In CSV File

In [22]:
import pandas as pd

fixtures = pd.read_csv('datasets/fixtures_full.csv')
fixtures

,timestamp,team1,team1_shape,team1_player1_name,team1_player2_name,team1_player3_name,team1_player4_name,team1_player5_name,team1_player6_name,team1_player7_name,...,team2_player4_name,team2_player5_name,team2_player6_name,team2_player7_name,team2_player8_name,team2_player9_name,team2_player10_name,team2_player11_name,result,score
0,"7:30 PM CT,September 12, 2020",FUL,4-2-3-1_L,Marek Rodak,Joe Bryan,Tim Ream,Michael Hector,Denis Odoi,Tom Cairney,Harrison Reed,...,Rob Holding,Ainsley Maitland-Niles,Granit Xhaka,Mohamed Elneny,Héctor Bellerín,Pierre-Emerick Aubameyang,Alexandre Lacazette,Willian,-1,0-3
1,"10:00 PM CT,September 12, 2020",CRY,4-4-2_L,Vicente Guaita,Tyrick Mitchell,Scott Dann,Cheikhou Kouyaté,Joel Ward,Jeff Schlupp,James McCarthy,...,Jack Stephens,Kyle Walker-Peters,Nathan Redmond,Oriol Romeu,James Ward-Prowse,William Smallbone,Danny Ings,Ché Adams,1,1-0
2,"12:30 AM CT,September 13, 2020",LIV,4-3-3-d_L,Alisson,Andy Robertson,Virgil van Dijk,Joe Gomez,Trent Alexander-Arnold,Georginio Wijnaldum,Jordan Henderson,...,Robin Koch,Luke Ayling,Kalvin Phillips,Jack Harrison,Mateusz Klich,Pablo Hernández,Hélder Costa,Patrick Bamford,1,4-3
3,"3:00 AM CT,September 13, 2020",WHU,4-2-3-1_L,Lukasz Fabianski,Aaron Cresswell,Angelo Ogbonna,Issa Diop,Ryan Fredericks,Declan Rice,Tomás Soucek,...,Jamaal Lascelles,Javier Manquillo,Allan Saint-Maximin,Isaac Hayden,Jonjo Shelvey,Jeff Hendrick,Andy Carroll,Callum Wilson,-1,0-2
4,"9:00 PM CT,September 13, 2020",WBA,5-4-1_L,Sam Johnstone,Kieran Gibbs,Dara O'Shea,Kyle Bartley,Semi Ajayi,Darnell Furlong,Grady Diangana,...,Wilfred Ndidi,Timothy Castagne,Nampalys Mendy,Harvey Barnes,Dennis Praet,Youri Tielemans,Ayoze Pérez,Jamie Vardy,-1,0-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259,"1:00 AM CT,May 15, 2022",POR,4-4-2_L,Diogo Costa,Zaidu Sanusi,Pepe2,Chancel Mbemba,Joao Mario1,Francisco Conceição,Bruno Costa,...,Bernardo Vital,Carles Soria,Bruno Lourenco,Luciano Vega,Joao Gamboa,André Franco,André Clóvis,Chiquinho2,1,2-0
4260,"1:00 AM CT,May 15, 2022",MAR,4-4-2_L,Miguel Silva,China,Zainadine Júnior,Jorge2,Cláudio Winck,Vítor Costa,Iván Rossi,...,Willyan Sotto,Fahd Moufi,Luquinha,Pedro Sá,Lucas Fernandes,Anderson Oliveira2,Fabrício,Aylton Boa Morte,-1,0-1
4261,"3:30 AM CT,May 15, 2022",SCP,3-4-3_L,Antonio Adán,Zouhair Feddal,Sebastián Coates,Gonçalo Inacio,Ruben Vinagre,João Palhinha,Matheus Nunes,...,João Afonso1,Rafael Ramos,Hidemasa Morita,Nené,Jean Patric,Lincoln,Carlos,Mohamed Bouldini,1,4-0
4262,"1:00 AM CT,May 16, 2022",FAM,4-2-3-1_L,Luiz Júnior,Rúben Lima,Dylan Batubinsika,Riccieli,Diogo Figueiras,Gustavo Assunção,David Tavares,...,Paulo Oliveira,Fabiano,André Horta,Elmutasem El Masrati,Fransérgio,Lucas Piazon,Ricardo Horta,Mario González,1,3-2
4263,"3:30 AM CT,May 16, 2022",GUI,4-3-3-d_L,Matous Trmal,Rafa2,Toni Borevkovic,Jorge Fernandes,Falaye Sacko,André,Alfa Semedo,...,Lucas Cunha,Zé Carlos,Paulinho5,Carvalho,Kanya Fujimoto,Samuel Lino,Fran Navarro,Bilel Aouacheria,1,5-0

### Remove empty row

In [23]:
nan_value = float("NaN")

print("shape before removing: ", fixtures.shape)

fixtures.replace("", nan_value, inplace=True)
fixtures.dropna(axis = 0, how = 'any', inplace=True)

print("after removing: ", fixtures.shape)

shape before removing:  (4264, 29)
after removing:  (4264, 29)

### Remove Duplicate

In [24]:
print("shape before removing: ", fixtures.shape)
fixtures.drop_duplicates(keep='first', inplace=True)
print("after removing: ", fixtures.shape)

shape before removing:  (4264, 29)
after removing:  (4264, 29)

### Convert Date Formats

In [25]:
fixtures['timestamp'] = pd.to_datetime(fixtures['timestamp'])

fixtures

C:\Users\sunny\anaconda3\lib\site-packages\dateutil\parser\_parser.py:1207: UnknownTimezoneWarning: tzname CT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

,timestamp,team1,team1_shape,team1_player1_name,team1_player2_name,team1_player3_name,team1_player4_name,team1_player5_name,team1_player6_name,team1_player7_name,...,team2_player4_name,team2_player5_name,team2_player6_name,team2_player7_name,team2_player8_name,team2_player9_name,team2_player10_name,team2_player11_name,result,score
0,2020-09-12 19:30:00,FUL,4-2-3-1_L,Marek Rodak,Joe Bryan,Tim Ream,Michael Hector,Denis Odoi,Tom Cairney,Harrison Reed,...,Rob Holding,Ainsley Maitland-Niles,Granit Xhaka,Mohamed Elneny,Héctor Bellerín,Pierre-Emerick Aubameyang,Alexandre Lacazette,Willian,-1,0-3
1,2020-09-12 22:00:00,CRY,4-4-2_L,Vicente Guaita,Tyrick Mitchell,Scott Dann,Cheikhou Kouyaté,Joel Ward,Jeff Schlupp,James McCarthy,...,Jack Stephens,Kyle Walker-Peters,Nathan Redmond,Oriol Romeu,James Ward-Prowse,William Smallbone,Danny Ings,Ché Adams,1,1-0
2,2020-09-13 00:30:00,LIV,4-3-3-d_L,Alisson,Andy Robertson,Virgil van Dijk,Joe Gomez,Trent Alexander-Arnold,Georginio Wijnaldum,Jordan Henderson,...,Robin Koch,Luke Ayling,Kalvin Phillips,Jack Harrison,Mateusz Klich,Pablo Hernández,Hélder Costa,Patrick Bamford,1,4-3
3,2020-09-13 03:00:00,WHU,4-2-3-1_L,Lukasz Fabianski,Aaron Cresswell,Angelo Ogbonna,Issa Diop,Ryan Fredericks,Declan Rice,Tomás Soucek,...,Jamaal Lascelles,Javier Manquillo,Allan Saint-Maximin,Isaac Hayden,Jonjo Shelvey,Jeff Hendrick,Andy Carroll,Callum Wilson,-1,0-2
4,2020-09-13 21:00:00,WBA,5-4-1_L,Sam Johnstone,Kieran Gibbs,Dara O'Shea,Kyle Bartley,Semi Ajayi,Darnell Furlong,Grady Diangana,...,Wilfred Ndidi,Timothy Castagne,Nampalys Mendy,Harvey Barnes,Dennis Praet,Youri Tielemans,Ayoze Pérez,Jamie Vardy,-1,0-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259,2022-05-15 01:00:00,POR,4-4-2_L,Diogo Costa,Zaidu Sanusi,Pepe2,Chancel Mbemba,Joao Mario1,Francisco Conceição,Bruno Costa,...,Bernardo Vital,Carles Soria,Bruno Lourenco,Luciano Vega,Joao Gamboa,André Franco,André Clóvis,Chiquinho2,1,2-0
4260,2022-05-15 01:00:00,MAR,4-4-2_L,Miguel Silva,China,Zainadine Júnior,Jorge2,Cláudio Winck,Vítor Costa,Iván Rossi,...,Willyan Sotto,Fahd Moufi,Luquinha,Pedro Sá,Lucas Fernandes,Anderson Oliveira2,Fabrício,Aylton Boa Morte,-1,0-1
4261,2022-05-15 03:30:00,SCP,3-4-3_L,Antonio Adán,Zouhair Feddal,Sebastián Coates,Gonçalo Inacio,Ruben Vinagre,João Palhinha,Matheus Nunes,...,João Afonso1,Rafael Ramos,Hidemasa Morita,Nené,Jean Patric,Lincoln,Carlos,Mohamed Bouldini,1,4-0
4262,2022-05-16 01:00:00,FAM,4-2-3-1_L,Luiz Júnior,Rúben Lima,Dylan Batubinsika,Riccieli,Diogo Figueiras,Gustavo Assunção,David Tavares,...,Paulo Oliveira,Fabiano,André Horta,Elmutasem El Masrati,Fransérgio,Lucas Piazon,Ricardo Horta,Mario González,1,3-2
4263,2022-05-16 03:30:00,GUI,4-3-3-d_L,Matous Trmal,Rafa2,Toni Borevkovic,Jorge Fernandes,Falaye Sacko,André,Alfa Semedo,...,Lucas Cunha,Zé Carlos,Paulinho5,Carvalho,Kanya Fujimoto,Samuel Lino,Fran Navarro,Bilel Aouacheria,1,5-0

In [26]:
fixtures.columns

Index(['timestamp', 'team1', 'team1_shape', 'team1_player1_name',
       'team1_player2_name', 'team1_player3_name', 'team1_player4_name',
       'team1_player5_name', 'team1_player6_name', 'team1_player7_name',
       'team1_player8_name', 'team1_player9_name', 'team1_player10_name',
       'team1_player11_name', 'team2', 'team2_shape', 'team2_player1_name',
       'team2_player2_name', 'team2_player3_name', 'team2_player4_name',
       'team2_player5_name', 'team2_player6_name', 'team2_player7_name',
       'team2_player8_name', 'team2_player9_name', 'team2_player10_name',
       'team2_player11_name', 'result', 'score'],
      dtype='object')

### Add 1 to results

In [27]:
fixtures['result'] = fixtures['result']+1

fixtures

,timestamp,team1,team1_shape,team1_player1_name,team1_player2_name,team1_player3_name,team1_player4_name,team1_player5_name,team1_player6_name,team1_player7_name,...,team2_player4_name,team2_player5_name,team2_player6_name,team2_player7_name,team2_player8_name,team2_player9_name,team2_player10_name,team2_player11_name,result,score
0,2020-09-12 19:30:00,FUL,4-2-3-1_L,Marek Rodak,Joe Bryan,Tim Ream,Michael Hector,Denis Odoi,Tom Cairney,Harrison Reed,...,Rob Holding,Ainsley Maitland-Niles,Granit Xhaka,Mohamed Elneny,Héctor Bellerín,Pierre-Emerick Aubameyang,Alexandre Lacazette,Willian,0,0-3
1,2020-09-12 22:00:00,CRY,4-4-2_L,Vicente Guaita,Tyrick Mitchell,Scott Dann,Cheikhou Kouyaté,Joel Ward,Jeff Schlupp,James McCarthy,...,Jack Stephens,Kyle Walker-Peters,Nathan Redmond,Oriol Romeu,James Ward-Prowse,William Smallbone,Danny Ings,Ché Adams,2,1-0
2,2020-09-13 00:30:00,LIV,4-3-3-d_L,Alisson,Andy Robertson,Virgil van Dijk,Joe Gomez,Trent Alexander-Arnold,Georginio Wijnaldum,Jordan Henderson,...,Robin Koch,Luke Ayling,Kalvin Phillips,Jack Harrison,Mateusz Klich,Pablo Hernández,Hélder Costa,Patrick Bamford,2,4-3
3,2020-09-13 03:00:00,WHU,4-2-3-1_L,Lukasz Fabianski,Aaron Cresswell,Angelo Ogbonna,Issa Diop,Ryan Fredericks,Declan Rice,Tomás Soucek,...,Jamaal Lascelles,Javier Manquillo,Allan Saint-Maximin,Isaac Hayden,Jonjo Shelvey,Jeff Hendrick,Andy Carroll,Callum Wilson,0,0-2
4,2020-09-13 21:00:00,WBA,5-4-1_L,Sam Johnstone,Kieran Gibbs,Dara O'Shea,Kyle Bartley,Semi Ajayi,Darnell Furlong,Grady Diangana,...,Wilfred Ndidi,Timothy Castagne,Nampalys Mendy,Harvey Barnes,Dennis Praet,Youri Tielemans,Ayoze Pérez,Jamie Vardy,0,0-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259,2022-05-15 01:00:00,POR,4-4-2_L,Diogo Costa,Zaidu Sanusi,Pepe2,Chancel Mbemba,Joao Mario1,Francisco Conceição,Bruno Costa,...,Bernardo Vital,Carles Soria,Bruno Lourenco,Luciano Vega,Joao Gamboa,André Franco,André Clóvis,Chiquinho2,2,2-0
4260,2022-05-15 01:00:00,MAR,4-4-2_L,Miguel Silva,China,Zainadine Júnior,Jorge2,Cláudio Winck,Vítor Costa,Iván Rossi,...,Willyan Sotto,Fahd Moufi,Luquinha,Pedro Sá,Lucas Fernandes,Anderson Oliveira2,Fabrício,Aylton Boa Morte,0,0-1
4261,2022-05-15 03:30:00,SCP,3-4-3_L,Antonio Adán,Zouhair Feddal,Sebastián Coates,Gonçalo Inacio,Ruben Vinagre,João Palhinha,Matheus Nunes,...,João Afonso1,Rafael Ramos,Hidemasa Morita,Nené,Jean Patric,Lincoln,Carlos,Mohamed Bouldini,2,4-0
4262,2022-05-16 01:00:00,FAM,4-2-3-1_L,Luiz Júnior,Rúben Lima,Dylan Batubinsika,Riccieli,Diogo Figueiras,Gustavo Assunção,David Tavares,...,Paulo Oliveira,Fabiano,André Horta,Elmutasem El Masrati,Fransérgio,Lucas Piazon,Ricardo Horta,Mario González,2,3-2
4263,2022-05-16 03:30:00,GUI,4-3-3-d_L,Matous Trmal,Rafa2,Toni Borevkovic,Jorge Fernandes,Falaye Sacko,André,Alfa Semedo,...,Lucas Cunha,Zé Carlos,Paulinho5,Carvalho,Kanya Fujimoto,Samuel Lino,Fran Navarro,Bilel Aouacheria,2,5-0

### Remove possible space before or behind names

In [28]:
# Remove possible space before or behind names
fixtures['team1_player1_name'] = fixtures['team1_player1_name'].str.strip()
fixtures['team1_player2_name'] = fixtures['team1_player2_name'].str.strip()
fixtures['team1_player3_name'] = fixtures['team1_player3_name'].str.strip()
fixtures['team1_player4_name'] = fixtures['team1_player4_name'].str.strip()
fixtures['team1_player5_name'] = fixtures['team1_player5_name'].str.strip()
fixtures['team1_player6_name'] = fixtures['team1_player6_name'].str.strip()
fixtures['team1_player7_name'] = fixtures['team1_player7_name'].str.strip()
fixtures['team1_player8_name'] = fixtures['team1_player8_name'].str.strip()
fixtures['team1_player9_name'] = fixtures['team1_player9_name'].str.strip()
fixtures['team1_player10_name'] = fixtures['team1_player10_name'].str.strip()
fixtures['team1_player11_name'] = fixtures['team1_player11_name'].str.strip()
fixtures['team2_player1_name'] = fixtures['team2_player1_name'].str.strip()
fixtures['team2_player2_name'] = fixtures['team2_player2_name'].str.strip()
fixtures['team2_player3_name'] = fixtures['team2_player3_name'].str.strip()
fixtures['team2_player4_name'] = fixtures['team2_player4_name'].str.strip()
fixtures['team2_player5_name'] = fixtures['team2_player5_name'].str.strip()
fixtures['team2_player6_name'] = fixtures['team2_player6_name'].str.strip()
fixtures['team2_player7_name'] = fixtures['team2_player7_name'].str.strip()
fixtures['team2_player8_name'] = fixtures['team2_player8_name'].str.strip()
fixtures['team2_player9_name'] = fixtures['team2_player9_name'].str.strip()
fixtures['team2_player10_name'] = fixtures['team2_player10_name'].str.strip()
fixtures['team2_player11_name'] = fixtures['team2_player11_name'].str.strip()

### Add position feature

In [29]:
positions = pd.read_csv('datasets/fixtures2positions.csv')

# Remove empty row
nan_value = float("NaN")

print("shape before removing: ", positions.shape)
positions.replace("", nan_value, inplace=True)

positions.dropna(axis = 0, how = 'any', inplace=True)
print("after removing: ", positions.shape)

positions.head()

shape before removing:  (32, 23)
after removing:  (32, 23)

,team_shape,player1_x,player1_y,player2_x,player2_y,player3_x,player3_y,player4_x,player4_y,player5_x,...,player7_x,player7_y,player8_x,player8_y,player9_x,player9_y,player10_x,player10_y,player11_x,player11_y
0,5-4-1_L,-24,0,-18,10,-20,5,-20,0,-20,...,-12,9,-12,3,-12,-3,-12,-9,-4,0
1,5-4-1_R,24,0,18,-10,20,-5,20,0,20,...,12,-9,12,-3,12,3,12,9,4,0
2,5-3-2_L,-24,0,-18,10,-20,5,-20,0,-20,...,-12,6,-12,0,-12,-6,-4,3,-4,-3
3,5-3-2_R,24,0,18,-10,20,-5,20,0,20,...,12,-6,12,0,12,6,4,-3,4,3
4,4-4-2_L,-24,0,-18,9,-20,3,-20,-3,-18,...,-12,3,-12,-3,-10,-9,-4,3,-4,-3

In [30]:
import numpy as np

# Add empty columns
fixtures['team1_positions_x'] = ""
fixtures['team1_positions_y'] = ""
fixtures['team2_positions_x'] = ""
fixtures['team2_positions_y'] = ""
fixtures['team1_positions_x'] = fixtures['team1_positions_x'].astype('object')
fixtures['team1_positions_y'] = fixtures['team1_positions_y'].astype('object')
fixtures['team2_positions_x'] = fixtures['team2_positions_x'].astype('object')
fixtures['team2_positions_y'] = fixtures['team2_positions_y'].astype('object')

# Adding position feature
for i, row in fixtures.iterrows():
    # Get positions of both teams
    pos = list(positions[positions['team_shape'] == row['team1_shape']].iloc[0][1:])
    pos_x = pos[::2]
    pos_y = pos[1::2]
    pos2 = list(positions[positions['team_shape'] == row['team2_shape']].iloc[0][1:])
    pos2_x = pos2[::2]
    pos2_y = pos2[1::2]
    
    # Add positions of both teams in dataframe    
    fixtures.at[i,'team1_positions_x'] = pos_x
    fixtures.at[i,'team1_positions_y'] = pos_y
    fixtures.at[i,'team2_positions_x'] = pos2_x
    fixtures.at[i,'team2_positions_y'] = pos2_y

In [31]:
fixtures.head()

,timestamp,team1,team1_shape,team1_player1_name,team1_player2_name,team1_player3_name,team1_player4_name,team1_player5_name,team1_player6_name,team1_player7_name,...,team2_player8_name,team2_player9_name,team2_player10_name,team2_player11_name,result,score,team1_positions_x,team1_positions_y,team2_positions_x,team2_positions_y
0,2020-09-12 19:30:00,FUL,4-2-3-1_L,Marek Rodak,Joe Bryan,Tim Ream,Michael Hector,Denis Odoi,Tom Cairney,Harrison Reed,...,Héctor Bellerín,Pierre-Emerick Aubameyang,Alexandre Lacazette,Willian,0,0-3,"[-24, -19, -21, -21, -19, -15, -15, -11, -9, -...","[0, 9, 3, -3, -9, 3, -3, 9, 0, -9, 0]","[24, 18, 20, 18, 12, 12, 12, 12, 6, 4, 6]","[0, -8, 0, 8, -9, -3, 3, 9, -8, 0, 8]"
1,2020-09-12 22:00:00,CRY,4-4-2_L,Vicente Guaita,Tyrick Mitchell,Scott Dann,Cheikhou Kouyaté,Joel Ward,Jeff Schlupp,James McCarthy,...,James Ward-Prowse,William Smallbone,Danny Ings,Ché Adams,2,1-0,"[-24, -18, -20, -20, -18, -10, -12, -12, -10, ...","[0, 9, 3, -3, -9, 9, 3, -3, -9, 3, -3]","[24, 18, 20, 20, 18, 10, 12, 12, 10, 4, 4]","[0, -9, -3, 3, 9, -9, -3, 3, 9, -3, 3]"
2,2020-09-13 00:30:00,LIV,4-3-3-d_L,Alisson,Andy Robertson,Virgil van Dijk,Joe Gomez,Trent Alexander-Arnold,Georginio Wijnaldum,Jordan Henderson,...,Mateusz Klich,Pablo Hernández,Hélder Costa,Patrick Bamford,2,4-3,"[-24, -18, -20, -20, -18, -12, -14, -12, -6, -...","[0, 9, 3, -3, -9, 3, 0, -3, 8, 0, -8]","[24, 19, 21, 21, 19, 15, -7, 9, 9, 7, 3]","[0, -9, -3, 3, 9, 0, -9, -3, 3, 9, 0]"
3,2020-09-13 03:00:00,WHU,4-2-3-1_L,Lukasz Fabianski,Aaron Cresswell,Angelo Ogbonna,Issa Diop,Ryan Fredericks,Declan Rice,Tomás Soucek,...,Jonjo Shelvey,Jeff Hendrick,Andy Carroll,Callum Wilson,0,0-2,"[-24, -19, -21, -21, -19, -15, -15, -11, -9, -...","[0, 9, 3, -3, -9, 3, -3, 9, 0, -9, 0]","[24, 18, 20, 20, 18, 10, 12, 12, 10, 4, 4]","[0, -9, -3, 3, 9, -9, -3, 3, 9, -3, 3]"
4,2020-09-13 21:00:00,WBA,5-4-1_L,Sam Johnstone,Kieran Gibbs,Dara O'Shea,Kyle Bartley,Semi Ajayi,Darnell Furlong,Grady Diangana,...,Dennis Praet,Youri Tielemans,Ayoze Pérez,Jamie Vardy,0,0-3,"[-24, -18, -20, -20, -20, -18, -12, -12, -12, ...","[0, 10, 5, 0, -5, -10, 9, 3, -3, -9, 0]","[24, 19, 21, 21, 19, 15, -7, 9, 9, 7, 3]","[0, -9, -3, 3, 9, 0, -9, -3, 3, 9, 0]"

In [32]:
# Check dtype of team1_positions, team2_positions is all int
results = []
for i, row in fixtures.iterrows():
    results.append(all(isinstance(x, np.int64) for x in row['team1_positions_x']))
    results.append(all(isinstance(x, np.int64) for x in row['team1_positions_y']))
    results.append(all(isinstance(x, np.int64) for x in row['team2_positions_x']))
    results.append(all(isinstance(x, np.int64) for x in row['team2_positions_y']))

In [33]:
# this should be true
print(all(results))

True

### Save CSV File

In [34]:
fixtures = fixtures[['timestamp', 
                     'team1', 'team1_shape', 'team1_positions_x', 'team1_positions_y', 'team1_player1_name', 'team1_player2_name', 'team1_player3_name', 'team1_player4_name', 'team1_player5_name', 'team1_player6_name', 'team1_player7_name', 'team1_player8_name', 'team1_player9_name', 'team1_player10_name', 'team1_player11_name', 
                     'team2', 'team2_shape', 'team2_positions_x', 'team2_positions_y', 'team2_player1_name', 'team2_player2_name', 'team2_player3_name', 'team2_player4_name', 'team2_player5_name', 'team2_player6_name', 'team2_player7_name', 'team2_player8_name', 'team2_player9_name', 'team2_player10_name', 'team2_player11_name', 
                     'result', 'score']]

In [35]:
header = list(fixtures.columns)

print(header)
print(len(header))

['timestamp', 'team1', 'team1_shape', 'team1_positions_x', 'team1_positions_y', 'team1_player1_name', 'team1_player2_name', 'team1_player3_name', 'team1_player4_name', 'team1_player5_name', 'team1_player6_name', 'team1_player7_name', 'team1_player8_name', 'team1_player9_name', 'team1_player10_name', 'team1_player11_name', 'team2', 'team2_shape', 'team2_positions_x', 'team2_positions_y', 'team2_player1_name', 'team2_player2_name', 'team2_player3_name', 'team2_player4_name', 'team2_player5_name', 'team2_player6_name', 'team2_player7_name', 'team2_player8_name', 'team2_player9_name', 'team2_player10_name', 'team2_player11_name', 'result', 'score']
33

In [36]:
fixtures.head()

,timestamp,team1,team1_shape,team1_positions_x,team1_positions_y,team1_player1_name,team1_player2_name,team1_player3_name,team1_player4_name,team1_player5_name,...,team2_player4_name,team2_player5_name,team2_player6_name,team2_player7_name,team2_player8_name,team2_player9_name,team2_player10_name,team2_player11_name,result,score
0,2020-09-12 19:30:00,FUL,4-2-3-1_L,"[-24, -19, -21, -21, -19, -15, -15, -11, -9, -...","[0, 9, 3, -3, -9, 3, -3, 9, 0, -9, 0]",Marek Rodak,Joe Bryan,Tim Ream,Michael Hector,Denis Odoi,...,Rob Holding,Ainsley Maitland-Niles,Granit Xhaka,Mohamed Elneny,Héctor Bellerín,Pierre-Emerick Aubameyang,Alexandre Lacazette,Willian,0,0-3
1,2020-09-12 22:00:00,CRY,4-4-2_L,"[-24, -18, -20, -20, -18, -10, -12, -12, -10, ...","[0, 9, 3, -3, -9, 9, 3, -3, -9, 3, -3]",Vicente Guaita,Tyrick Mitchell,Scott Dann,Cheikhou Kouyaté,Joel Ward,...,Jack Stephens,Kyle Walker-Peters,Nathan Redmond,Oriol Romeu,James Ward-Prowse,William Smallbone,Danny Ings,Ché Adams,2,1-0
2,2020-09-13 00:30:00,LIV,4-3-3-d_L,"[-24, -18, -20, -20, -18, -12, -14, -12, -6, -...","[0, 9, 3, -3, -9, 3, 0, -3, 8, 0, -8]",Alisson,Andy Robertson,Virgil van Dijk,Joe Gomez,Trent Alexander-Arnold,...,Robin Koch,Luke Ayling,Kalvin Phillips,Jack Harrison,Mateusz Klich,Pablo Hernández,Hélder Costa,Patrick Bamford,2,4-3
3,2020-09-13 03:00:00,WHU,4-2-3-1_L,"[-24, -19, -21, -21, -19, -15, -15, -11, -9, -...","[0, 9, 3, -3, -9, 3, -3, 9, 0, -9, 0]",Lukasz Fabianski,Aaron Cresswell,Angelo Ogbonna,Issa Diop,Ryan Fredericks,...,Jamaal Lascelles,Javier Manquillo,Allan Saint-Maximin,Isaac Hayden,Jonjo Shelvey,Jeff Hendrick,Andy Carroll,Callum Wilson,0,0-2
4,2020-09-13 21:00:00,WBA,5-4-1_L,"[-24, -18, -20, -20, -20, -18, -12, -12, -12, ...","[0, 10, 5, 0, -5, -10, 9, 3, -3, -9, 0]",Sam Johnstone,Kieran Gibbs,Dara O'Shea,Kyle Bartley,Semi Ajayi,...,Wilfred Ndidi,Timothy Castagne,Nampalys Mendy,Harvey Barnes,Dennis Praet,Youri Tielemans,Ayoze Pérez,Jamie Vardy,0,0-3

In [37]:
fixtures.to_csv('pre-processed/fixtures.csv', index = False, header = header, encoding='utf-8-sig')

### Copy to data/raw

In [38]:
from shutil import copyfile

src = 'pre-processed/fixtures.csv'
dest = 'data/raw/fixtures.csv'

copyfile(src, dest)

'data/raw/fixtures.csv'

### Final Check

In [39]:
np.where(fixtures.applymap(lambda x: x == ''))

(array([], dtype=int64), array([], dtype=int64))

In [40]:
np.where(pd.isnull(fixtures))

(array([], dtype=int64), array([], dtype=int64))